### ISSUE TITLE
HostAny does not listen for IPv6 connections

### ISSUE THREAD

**Issue by amir-sabbaghi** [k0001/network-simple#22]
There is `HostIPv4` which listens for IPv4 connections.
There is `HostIPv6` which listens for IPv6 connections.
And there is `HostAny` which should ideally listen for both. But it currently does not. It is equivalent to `HostIPv4`.
If you set `AI_V4MAPPED` flag on an IPv6 socket, it can listen for both IPv4 and IPv6 connections.

**Comment by k0001** [comment]
This has been implemented already. Thanks. Sorry for the incredibly long delay.
