### ISSUE TITLE
Server does not output to console.

### ISSUE THREAD

**Issue by PiotrJustyna** [k0001/network-simple#24]
First of all, thank you for putting the library together - super useful!

I've been playing with the server code for a while now and for some reason, it doesn't always print to the console when I would expect it to. Sample code:

```haskell
module Main where

import Network.Simple.TCP

main :: IO ()
main = serve (Host "127.0.0.1") "4242" $ \(connectionSocket, remoteAddr) -> do
  putStrLn $ "TCP connection established from " ++ show remoteAddr
```

The server is running just fine, I can connect both from telnet and from a client written in ```Network.Simple.TCP```. Same happens with the examples, e.g. https://github.com/k0001/network-simple/blob/master/examples/echo-tcp.hs. Am I missing something?

Environment: Windows 10, Stack

**Comment by k0001** [comment]
Piotr,

I suspect the issue you are having is not related to network-simple, but to
how stdout buffering is configured for your application. See
https://hackage.haskell.org/package/base-4.9.0.0/docs/System-IO.html#g:12

Try enabling line buffering explicitly and see if that improves things.

**Comment by PiotrJustyna** [comment]
Thanks. Let me try that and I'll update the issue with me findings.

**Comment by PiotrJustyna** [comment]
Thank you, thank was it :smile: 

If anybody else gets stuck on this issue, here's a sample piece of code checking and then setting the desired buffering type:

```haskell
module Main where

import Network.Simple.TCP
import System.IO

main :: IO ()
main = do
  bufferingModeBefore <- hGetBuffering stdout
  putStrLn $ "Current buffering mode: " ++ (show bufferingModeBefore)
  hSetBuffering stdout NoBuffering
  bufferingModeAfter <- hGetBuffering stdout
  putStrLn $ "Current buffering mode: " ++ (show bufferingModeAfter)
  serve (Host "127.0.0.1") "4242" $ \(connectionSocket, remoteAddr) -> do
    putStrLn $ "TCP connection established from " ++ show remoteAddr
```

![image](https://cloud.githubusercontent.com/assets/6170837/18487744/4e3e4e7a-79ee-11e6-8bae-25d2f659fc29.png)
