### ISSUE TITLE
build failure 0.4.1

### ISSUE THREAD

**Issue by grimace** [k0001/network-simple#26]
I'm just a newbie, but I can't get this to build:

> src/Network/Simple/Internal.hs:55:24:
>    Not in scope: ‘NS.tupleToHostAddress’

and since I have other modules that depend on network-simple, I'm just stuck!

**Comment by k0001** [comment]
It sounds like you are using a version of 'network' older than 2.6.3.0. I suggest upgrading if this is blocking you. I'll try and add some backwards compatibility later. Thanks.

**Comment by grimace** [comment]
I was able to get my project to build by bumping the network version.  Tho, in the 0.4.1  .cabal file network version is:   " network      (>=2.3)".  I couldn't build this project until I bumped the version in this file:  
network-simple/network-simple.cabal
Should this be updated?
Thx.

**Comment by k0001** [comment]
Yes, that lower bound should be added back.
