### ISSUE TITLE
recv buffer keeping connection open despite closeSock call

### ISSUE THREAD

**Issue by ancarda** [k0001/network-simple#27]
I'm having some trouble using this package when the server side tries to close the socket. I've called `closeSock` to close a TCP connection but have found the connection stays open due to a previous `recv` function call.

When the client side sends enough bytes specified by recv, the connection is closed right away, but without sending those bytes, the connection will hang forever. The client can later send bytes and the connection will close as expected.

Below is a minimal example that recreates the issue:

```haskell
module Main where

import Network.Simple.TCP
import Data.Maybe
import Data.ByteString.Char8 (pack)

main = do
  serve (Host "127.0.0.1") "8080" $ \(sock, remoteAddr) -> do
    send sock $ pack "Type 4 bytes.\n";

    x <- recv sock 4
    let input = fromMaybe (pack "") x
    send sock input

    send sock $ pack "\nClosing Connection.\n"
    closeSock sock
```

Please observe if you connect and send 4 or more bytes, only 4 bytes will be echoed back, and the server will close the connection. When less than 4 bytes are specified, the connection will remain open -- despite `closeSock` being called -- until the remaining bytes are sent.

```
$ nc 127.0.0.1 8080
Type 4 bytes.
test
test
Closing Connection.

$ nc 127.0.0.1 8080
Type 4 bytes.
huh
huh

Closing Connection.
^C (manually killed)

$ nc 127.0.0.1 8080
Type 4 bytes.
huh
huh

Closing Connection.
? (process closed by itself)
```

Am I misunderstanding how to use this package or is this a bug?

**Comment by Wizek** [comment]
I also remember running into this some time ago, and being confused. Any ideas, @k0001?

**Comment by MathiasVP** [comment]
I'm also currently running into this problem :( Any updates on this?

**Comment by ancarda** [comment]
Good timing to ask, I had an idea earlier today which I will explore tonight if I get the chance.

**Comment by k0001** [comment]
I'm investigating this at the moment. Thanks for the excellent issue report.

**Comment by k0001** [comment]
There is a known bug in `network-2.6.3.4` when closing a socket. Are you using this version by any chance?

**Comment by ancarda** [comment]
The only thing I have in my cabal file is `network-simple >= 0.4.1` -- do you know how I can check the dependency for `network`?

**Comment by k0001** [comment]
You can check with 'ghc-pkg list | grep network' within your development environment.

**Comment by ancarda** [comment]
I am using these versions:

```
    network-2.7.0.2
    network-simple-0.4.1
```

I had a thought about this earlier today (I just got back from work), and I suspect most, or possibly all, of what I am seeing is due to how netcat (`nc`) works. If I adjust the server to not receive any input, netcat will still hang even though the connection closes immediately after sending "Type 4 bytes". When using `nc -d` (disable stdin), netcat will exit as soon as the connection is closed.

That could explain what I'm seeing:

If you kill the server process while `nc -d` is running, it'll exit right away; this essentially simulates what a `close` would do; send a TCP RST, or otherwise signal to the client the connection is closing. If you don't have `-d`, netcat is waiting for stdin; as it, unlike telnet, uses line buffering.

If you compare to using `telnet`; it works as expected:

```
$ telnet 127.0.0.1 8080
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
Type 4 bytes.
abcd 
abcd
Closing Connection.
Connection closed by foreign host.

$ telnet 127.0.0.1 8080
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
Type 4 bytes.
ab
ab

Closing Connection.
Connection closed by foreign host.
```

Note even though I only typed 2 bytes, the connection closed right after sending some input to the server.

I'm going to close this issue as I think this is working as expected. I hope this is useful, @MathiasVP.

**Comment by k0001** [comment]
I tend to agree with @ancarda. This behavior seems to be specific to `nc`. 

Somewhat related: I pushed some changes to `master` improving error handling and connection shutdown in general throughout the library. I will give a test to these changes soon and then upload a new version of the library to Hackage. Notice that even after these improvements, the `nc` situation is the same.

**Comment by k0001** [comment]
Unrelated update: I just pushed `network-simple-0.4.2` to Hackage, it mostly improves internal error handling.
