### ISSUE TITLE
support for network-3.0.0.1

### ISSUE THREAD

**Issue by hdb3** [k0001/network-simple#30]
I looked at this upgrade to >= network-3.0.0.1 - there is no direct dependency here, but the socks library is problematic, partly because of the breakout of Network-BSD, but not only that. (socks relies on a PortID imported from Network, but neither Network nor PortID exist anymore.....)
I resolved my requirement by removing the socks5 code and dependency in network-simple, however that might not suit others!
I suspect that socks library will need to change for network-3.0......

**Comment by hvr** [comment]
For the record, I've fixed up the inaccurate metadata (see https://hackage.haskell.org/package/network-simple-0.4.3/revisions/) to prevent `network-simple`'s build-plans from regressing today (see
Based on https://matrix.hackage.haskell.org/package/network-simple@1555938426 )

**Comment by k0001** [comment]
Dear Herbert, thanks for letting me know.

I will upload a new compatible version as soon as the 'socks' library is
updates.

**Comment by shulhi** [comment]
@k0001 I have a working version that is compatible with `network > 3`, you can see the diff here https://github.com/k0001/network-simple/compare/master...plow-technologies:shulhi-update-network-socks

I like to PR this since we are using this at work. If you think the changes are okay, I can make a PR with what I have.

**Comment by k0001** [comment]
network-simple-0.4.4 has been uploaded to hackage, and is now compatible with the newest version of socks. Thanks!

**Comment by k0001** [comment]
@shulhi I just noticed your comment offering your changes and a PR. Sorry, I missed it before, but I am nonetheless very thankful for your offer :)

**Comment by hvr** [comment]
@k0001 the latest network-simple-0.4.4 release doesn't seem to be compatible, see https://matrix.hackage.haskell.org/package/network-simple@1559983336

**Comment by k0001** [comment]
Thanks for letting me know!
