### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by erikd** [k0001/network-simple#32]
I am running into this:
```
src/Network/Simple/Internal.hs:24:1: error:
    Could not load module ‘Network.BSD’
    It is a member of the hidden package ‘network-bsd-2.8.1.0’.
    Perhaps you need to add ‘network-bsd’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘network-2.8.0.1’.
    Perhaps you need to add ‘network’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘network-2.8.0.1’.
    Perhaps you need to add ‘network’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
   |
24 | import qualified Network.BSD as NS (getServicePortNumber)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
which seems to be fixed in git.

**Comment by erikd** [comment]
I am currently using the following in my `cabal.project` file.
```
source-repository-package
  type: git
  location: https://github.com/k0001/network-simple
  tag: db274d137fc92dd32aff32ecae025060ccb1d7f7
```

**Comment by k0001** [comment]
Hey @erikd, thanks for this. 

I haven't uploaded this yet because I haven't had the time to check that this is building with various `network` versions, and update the Nix builds accordingly. Sorry. I'll do it as soon as possible.

**Comment by erikd** [comment]
Easiest way to make sure its building with multiple GHC versions is to do so in CI.

Interested in a patch to the travis setup for that?

**Comment by k0001** [comment]
There was a CI, but I haven't kept it up to date. I'll add different
configurations to the nix setup as soon as possible and make sure the CI
uses that. Thanks!

**Comment by erikd** [comment]
I have a 30 line `.travis.yaml` script that runs in just about any Haskell project and tests with multiple compilers. Will take me under a minute to raise the PR if you want it.

**Comment by k0001** [comment]
Alright, let's do it! Thanks.

**Comment by k0001** [comment]
Done! Thanks @erikd!!

https://hackage.haskell.org/package/network-simple-0.4.5

**Comment by erikd** [comment]
:100:

**Comment by erikd** [comment]
And don't forget to push your local changes to github :).

**Comment by k0001** [comment]
Done :) thanks for the reminder. It's been a long day.
