### ISSUE TITLE
Missing dependency on network-bsd

### ISSUE THREAD

**Issue by newhoggy** [k0001/network-simple#35]
```
src/Network/Simple/Internal.hs:24:1: error:
    Could not load module ‘Network.BSD’
    It is a member of the hidden package ‘network-bsd-2.8.1.0’.
    Perhaps you need to add ‘network-bsd’ to the build-depends in your .cabal file.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
24 | import qualified Network.BSD as NS (getServicePortNumber)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by newhoggy** [comment]
This is for `network-simple-0.4.4`

**Comment by hsenag** [comment]
I got the same problem, and it's showing as failing [in the matrix builder](https://matrix.hackage.haskell.org/#/package/network-simple).

Maybe you could do a hackage revision for 0.4.4 to add an upper bound on the `network` version?

**Comment by sjakobi** [comment]
As a Hackage trustee, I have made a revision for v0.4.4: https://hackage.haskell.org/package/network-simple-0.4.4/revisions/
